remote_theme: pages-themes/merlot@v0.2.0
plugins:
  - jekyll-remote-theme
title: [ Nutrameg Comprehensive Cake Guide ]
description: [ All rules and guidelines in this document apply to Nutrameg people and family. ]
