remote_theme: pages-themes/merlot@v0.2.0
plugins:
  - jekyll-remote-theme
title: [Nutrameg's Comprehensive Cake Guide]
description: [All rules and guidelines on this document applys to Nutrameg people and family 💚]
show_downloads: ["false"]
